export const menuItems = [{
        id: 1,
        label: "Menu",
        isTitle: true,
        user: [],
    },
    {
        id: 2,
        label: "Home",
        icon: "bx-home-circle",
        link: "/home",
        component: "Home/Index",
        name: "Home",
        user: [],
    },
    {
        id: 3,
        label: "Specialists",
        icon: "bx-user-circle",
        link: "/specialists",
        component: "Specialists/Index",
        name: "Specialists",
        user: ['Super Administrator'],
    },
    {
        id: 3,
        label: "Teachers",
        icon: "bxs-face",
        link: "/teachers",
        component: "Teachers/Index",
        name: "Teachers",
        user: ['Super Administrator'],
    },
    {
        id: 3,
        label: "Schools",
        icon: "bxs-school",
        link: "/schools",
        component: "Schools/Index",
        name: "Schools",
        user: ['Super Administrator'],
    },
    // {
    //     id: 10,
    //     label: "Group Leaders",
    //     icon: "bx-user-circle",
    //     link: "/group",
    //     component: "Group/Index",
    //     name: "Group",
    //     user: ['Super Administrator'],
    // },
    // {
    //     id: 11,
    //     label: "Team Leaders",
    //     icon: "bx-user-circle",
    //     link: "/team",
    //     component: "Team/Index",
    //     name: "Team",
    //     user: ['Region Leader'],
    // },
    // {
    //     id: 12,
    //     label: "Loan Specialist",
    //     icon: "bx-user-circle",
    //     link: "/specialist",
    //     component: "Specialist/Index",
    //     name: "Specialist",
    //     user: ['Team Leader'],
    // },
];